---
chicon_credentials:
  - env_var: DEVISE_SECRET
    command: "$(aws secretsmanager get-secret-value --secret-id {{ devise_secret }} | jq -r .SecretString)"
  - env_var: JWT_SECRET
    command: "$(aws secretsmanager get-secret-value --secret-id {{ jwt_secret }} | jq -r .SecretString)"
  - env_var: SMTP_PASSWORD
    command: "$(aws secretsmanager get-secret-value --secret-id {{ smtp_provider_secret }} | jq -r .SecretString)"
  - env_var: POSTGRES_PASSWORD
    command: "$(aws secretsmanager get-secret-value --secret-id {{ role_db_secret }} | jq -r .SecretString)"
  - env_var: SIDEKIQ_PASSWORD
    command: "$(aws secretsmanager get-secret-value --secret-id {{ sidekiq_secret }} | jq -r .SecretString)"
  - env_var: STRIPE_PUBLIC_KEY
    command: "$(aws secretsmanager get-secret-value --secret-id {{ stripe_secret }} | jq -r '.SecretString | fromjson | .pk')"
  - env_var: STRIPE_PRIVATE_KEY
    command: "$(aws secretsmanager get-secret-value --secret-id {{ stripe_secret }} | jq -r '.SecretString | fromjson | .sk')"
