#cloud-config
package_update: true
package_upgrade: true

packages:
  - awscli
  - build-essential
  - docker-compose
  - docker.io
  - libpq-dev
  - jq
  - postgresql-client-12
  - python-is-python3
  - python3
  - python3-dev
  - python3-pip
  - ruby
  - tmux
  - wget

write_files:
  - encoding: b64
    content: "${instance_launch_script}"
    path: /var/lib/cloud/scripts/per-instance/00-bootstrap.sh
    permissions: '0755'

  - encoding: b64
    content: "${install_codedeploy_script}"
    path: /var/lib/cloud/scripts/per-instance/01-install-codedeploy.sh
    permissions: '0755'

