repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.30.0
    hooks:
      - id: terraform_fmt
