repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.19.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

