#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker
  - python3
  - python3-devel
  - tmux
  - postgresql
  - jq

runcmd:
 - systemctl start docker
 - systemctl enable docker
 - curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
 - chmod +x /usr/local/bin/docker-compose
 - usermod -a -G docker ec2-user
 - "yum -y groupinstall \"Development Tools\""
 - pip3 install pgcli psycopg2-binary keyrings.alt boto3 'awscli>=1.15'


write_files:
  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/${db_username}/${stage} | jq -r .SecretString)
        exec pgcli -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/db
    permissions: '0755'

  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/${db_username}/${stage} | jq -r .SecretString)
        exec psql -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/psql.reg
    permissions: '0755'

  - content: |
        #!/bin/bash
        export KANSA_PG_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/kansa/${stage} | jq -r .SecretString)
        export HUGO_PG_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/hugo/${stage} | jq -r .SecretString)
        export RAAMI_PG_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/raami/${stage} | jq -r .SecretString)
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/${db_admin_username}/${stage} | jq -r .SecretString)
        exec psql -h ${db_hostname} -U ${db_admin_username} ${db_name} "$@"
    path: /usr/local/bin/psql.admin
    permissions: '0755'

  - content: |
        set-option -g prefix C-o
        bind-key C-o send-key C-o
    path: /etc/tmux.conf
    permissions: '0644'

  - content: |
        export AWS_DEFAULT_REGION=us-west-2
    path: /etc/profile.d/set-aws-region.sh
    permissions: '0644'

output : { all : '| tee -a /var/log/cloud-init-output.log' }
