#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker
  - python3
  - python3-devel
  - tmux
  - postgresql

runcmd:
 - systemctl start docker
 - systemctl enable docker
 - curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
 - chmod +x /usr/local/bin/docker-compose
 - usermod -a -G docker ec2-user
 - "yum -y groupinstall \"Development Tools\""
 - pip3 install pgcli psycopg2-binary


write_files:
  - content: |
        #!/bin/bash
        export PGPASSWORD='${db_password}'
        exec pgcli -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/db
    permissions: '0755'

  - content: |
        #!/bin/bash
        export PGPASSWORD='${db_password}'
        exec psql -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/psql.reg
    permissions: '0755'

  - content: |
        #!/bin/bash
        export KANSA_PG_PASSWORD=${db_kansa_password}
        export HUGO_PG_PASSWORD=${db_hugo_password}
        export RAAMI_PG_PASSWORD=${db_raami_password}
        export PGPASSWORD='${db_admin_password}'
        exec psql -h ${db_hostname} -U ${db_admin_username} ${db_name} "$@"
    path: /usr/local/bin/psql.admin
    permissions: '0755'

  - content: |
        set-option -g prefix C-o
        bind-key C-o send-key C-o
    path: /etc/tmux.conf
    permissions: '0644'

output : { all : '| tee -a /var/log/cloud-init-output.log' }
