---
- name: "[wordpress] Create the service user"
  user:
    name: wordpress
    groups:
      - chicago
  register: service_user
  become: yes

- name: get chicago gid
  getent:
    database: group
    key: chicago
  check_mode: no

- name: Ensure the config directories are present
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: wordpress
    group: chicago
  with_items:
    - "{{ chicon_home }}/etc/wordpress"
  become: yes

- name: Define the default service Docker volumes
  set_fact:
    _wordpress_docker_volumes:
      - "{{ chicon_home }}/etc/wordpress:/config"

- name: Append any additional volume mounts
  set_fact:
    _wordpress_docker_volumes: "{{ _wordpress_docker_volumes }} + {{ wordpress_additional_volumes }}"

- name: Define the default Docker environment variables
  set_fact:
    _wordpress_environment_vars:
      PGID: "{{ service_user.uid }}"
      PUID: "{{ getent_group.chicago[1] }}"

- name: Append any additional environment variables
  set_fact:
    _wordpress_environment_vars: "{{ _wordpress_environment_vars | combine(wordpress_additional_environment_variables) }}"

- name: Ensure the docker-compose template directory exists
  file:
    state: directory
    path: "{{ chicon_home }}/app/wordpress"
  become: yes

- name: Ensure this service's docker-compose template is present
  template:
    src: docker-compose.yml.j2
    dest: "{{ chicon_home }}/app/wordpress/docker-compose.yml"
  become: yes
  notify: restart site

- name: Set up a unit file for the service
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/wordpress.service
  become: yes

- name: reload services
  systemd:
    daemon_reload: yes
  become: yes

- name: Ensure the service container(s) is/are started
  systemd:
    name: wordpress
    enabled: yes
    state: started
  become: yes

- name: Set up caddy forwarder
  template: src=wordpress.conf.j2 dest={{ chicon_home }}/etc/sites-enabled/wordpress.conf owner=root group=chicago mode=0644
  become: yes
  notify: reload webserver
