admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm
  - username: rgb
    public_key: "{{ lookup('file', 'rgb.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm
  - username: balen
    public_key: "{{ lookup('file', 'henry.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm
  - username: mike
    public_key: "{{ lookup('file', 'mike.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

application_fqdn: "planorama{{fqdn_suffix}}.chicon.org"
role_db_secret: "{{ planorama_db_secret}}"
