ansible_user: ubuntu

admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

caddy_architecture: amd64
caddy_use_test_endpoint: no

stage: blog
prompt_color_code: "32"
prompt_color_hex: "50fa7a"

external_hostname: infra.blog.chicon.org
wordpress_fqdn_list:
  - chicagoworldconbid.org
  - bid.chicon.org
  - www.chicagoworldconbid.org

registration_db_secret: BOGON
