admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

  - username: lasiorhine
    public_key: "{{ lookup('file', 'victoria.pub')}}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

  - username: davidm
    public_key: "{{ lookup('file', 'davidm.pub')}}"
    sudo: yes
    extra_groups:
      - docker
      - chicago

ansible_user: ubuntu
application_fqdn: "registration{{fqdn_suffix}}.chicon.org"
external_hostname: "infra{{fqdn_suffix}}.chicon.org"
external_destination: "https://chicagoworldconbid.org"

registration_instalment_min: 5000
registration_instalment_increment: 3000
role_db_secret: "{{ registration_db_secret}}"

journald_cloudwatch_logs_log_group: "Registration/{{ stage }}"
journald_cloudwatch_logs_units:
  - wellington
  - caddy
