admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

  - username: lasiorhine
    public_key: "{{ lookup('file', 'victoria.pub')}}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

ansible_user: ubuntu
application_fqdn: "registration{{fqdn_suffix}}.chicon.org"
external_hostname: "infra{{fqdn_suffix}}.chicon.org"
external_destination: "https://chicagoworldconbid.org"

registration_instalment_min: 3000
registration_instalment_increment: 3000
