admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

caddy_architecture: amd64
caddy_use_test_endpoint: no

stage: dev
prompt_color_code: "34"

external_hostname: infra.dev.chicon.org
heimdall_fqdn: dashboard.dev.chicon.org
wellington_fqdn: registration.dev.chicon.org
wellington_docker_version: "staging"

registration_db_name: registration_dev
registration_db_username: registration_dev

devise_secret: Chicon8/tokens/session/dev
jwt_secret: Chicon8/tokens/jwt/dev
sendgrid_secret: Chicon8/sendgrid_api_key/dev
registration_db_secret: Chicon8/db/registration_dev/registration_dev_admin/dev
sidekiq_secret: Chicon8/sidekiq_password/dev
stripe_secret: Chicon8/stripe_api_key/dev
