caddy_architecture: amd64
caddy_use_test_endpoint: no

stage: staging
prompt_color_code: "34"
prompt_color_hex: "bd93f8"

heimdall_fqdn: dashboard.staging.chicon.org
fqdn_suffix: ".staging"
wellington_docker_version: "staging"
planorama_docker_version: "manual-ci"

registration_db_name: registration_dev
registration_db_username: registration_dev

# sendgrid config
smtp_server: smtp.mailgun.org
smtp_user_name: postmaster@comms.chicon.org
smtp_port: 587

devise_secret: Chicon8/tokens/session/staging
jwt_secret: Chicon8/tokens/jwt/staging
# smtp_provider_secret: Chicon8/sendgrid_api_key/staging
smtp_provider_secret: Chicon8/mailgun_smtp/staging
registration_db_secret: Chicon8/db/registration_dev/registration_dev_admin/staging
sidekiq_secret: Chicon8/sidekiq_password/staging
stripe_secret: Chicon8/stripe_api_key/staging

registration_contacts:
  registration_email: it+registration@{{ domain_name }}
  treasurer_email: it+treasurer@{{ domain_name }}
  maintainer_email: it+maintainer@{{ domain_name }}
  hugo_help_email: it+hugo@{{ domain_name }}
  hugo_admin_email: it+hugo-admin@{{ domain_name }}
