admin_users:
  - username: offby1
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    sudo: yes
    extra_groups:
      - docker
      - chicago
      - adm

caddy_architecture: amd64
caddy_use_test_endpoint: no

stage: prod
prompt_color_code: "31"
prompt_color_hex: "f85454"

heimdall_fqdn: dashboard.chicon.org
fqdn_suffix: ""
wellington_docker_version: "release"

registration_db_name: registration_prod
registration_db_username: registration_prod
registration_preview: no

devise_secret: Chicon8/tokens/session/prod
jwt_secret: Chicon8/tokens/jwt/prod
sendgrid_secret: Chicon8/sendgrid_api_key/prod
registration_db_secret: Chicon8/db/registration/registration_admin/prod
sidekiq_secret: Chicon8/sidekiq_password/prod
stripe_secret: Chicon8/stripe_api_key/prod

journald_cloudwatch_logs_log_group: Registration/prod
journald_cloudwatch_logs_units:
  - wellington
  - caddy

registration_contacts:
  registration_email: registration@{{ domain_name }}
  treasurer_email: treasurer@{{ domain_name }}
  maintainer_email: it@{{ domain_name }}
  hugo_help_email: hugo-help@{{ domain_name }}
  hugo_admin_email: hugo-admin@{{ domain_name }}
