caddy_architecture: amd64
caddy_use_test_endpoint: no

stage: prod
prompt_color_code: "31"
prompt_color_hex: "f85454"

heimdall_fqdn: dashboard.chicon.org
fqdn_suffix: ""
wellington_docker_version: "release"
planorama_docker_version: "latest"

registration_db_name: registration_prod
registration_db_username: registration_prod
registration_preview: no

planorama_db_name: planorama_prod
planorama_db_username: planorama_prod
planorama_preview: yes

# sendgrid config
smtp_server: smtp.mailgun.org
smtp_user_name: postmaster@comms.chicon.org
smtp_port: 587

devise_secret: Chicon8/tokens/session/prod
jwt_secret: Chicon8/tokens/jwt/prod
# smtp_provider_secret: Chicon8/sendgrid_api_key/prod
smtp_provider_secret: Chicon8/mailgun_smtp/prod
registration_db_secret: Chicon8/db/registration/registration_admin/prod
planorama_db_secret: Chicon8/db/planorama_prod/planorama_prod/prod
sidekiq_secret: Chicon8/sidekiq_password/prod
stripe_secret: Chicon8/stripe_api_key/prod

registration_contacts:
  registration_email: registration@{{ domain_name }}
  treasurer_email: treasurer@{{ domain_name }}
  maintainer_email: it@{{ domain_name }}
  hugo_help_email: hugo-help@{{ domain_name }}
  hugo_admin_email: hugo-admin@{{ domain_name }}

programming_contacts:
  maintainer_email: henry.balen@{{ domain_name }}
  programming_email: programming@{{ domain_name }}
