---
- name: install user support packages
  apt:
    pkg:
      - acl
      - hub
      - direnv
      - python3-venv
      - libssl-dev
      - mosh
    state: present

- name: "[admin] enable passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: "[admin] override our skel files"
  copy:
    src: dot_bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: 0644

- name: "[admin] add user"
  become: yes
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    state: present
  with_items: "{{ admin_users }}"

- name: "[admin] authorize key for user"
  become: yes
  authorized_key:
    key: "{{ item.public_key }}"
    user: "{{ item.username }}"
    manage_dir: yes
  with_items: "{{ admin_users }}"

- name: "[admin] add sudo access for user"
  become: yes
  user:
    name: "{{ item.username }}"
    append: yes
    groups:
      - sudo
  when: item.sudo
  with_items: "{{ admin_users }}"

- name: "[admin] add additional groups for user"
  become: yes
  user:
    name: "{{ item.username }}"
    append: yes
    groups: "{{ item.extra_groups }}"
  with_items: "{{ admin_users }}"

- name: Add profile entry to enable direnv
  become: yes
  copy:
    src: direnv_profile
    dest: /etc/profile.d/direnv.sh
    owner: root
    group: root
    mode: 0644

- name: Set up source checkout location
  file:
    path: "{{ chicon_home }}/src"
    state: directory
    mode: 0770
    owner: "{{ admin_users[0].username }}"
    group: chicago

- name: Set up the .envrc file in the checkout with postgres support
  template:
    src: src.envrc.j2
    dest: "{{ chicon_home }}/src/.envrc"
    mode: 0660
    owner: "{{ admin_users[0].username }}"
    group: chicago

- name: download rbenv installer
  get_url:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    dest: "{{ chicon_home }}/bin/rbenv-installer"

- name: install rbenv for admin users
  become: yes
  become_user: "{{ item.username }}"
  shell:
    cmd: "cat {{ chicon_home }}/bin/rbenv-installer | bash"
    creates: "/home/{{ item.username }}/.rbenv/bin/rbenv"
  with_items: "{{ admin_users }}"
  ignore_errors: yes
