---
- name: reload webserver
  service:
    name: caddy
    state: reloaded
  become: yes
    
- name: reload services
  systemd:
    daemon_reload: yes
  become: yes

- name: restart site
  systemd:
    name: wordpress
    state: restarted
    
