plugin: aws_ec2
regions:
  - us-west-2
filters:
  tag:Project: Chicon8
  tag:Environment:
    - dev

keyed_groups:
  - prefix: stage
    key: tags.Environment

  - prefix: app
    key: tags.Application

  # - prefix: tag
  #   key: tags

hostnames:
  - dns-name
  - private-ip-address


