#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker
  - python3
  - python3-devel
  - tmux
  - postgresql
  - jq

runcmd:
  - yum update
  # Juuust in case, try re-install all of those packages above
  - yum -y install docker python3 python3-devel tmux postgresql jq ruby wget

  # Install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - usermod -a -G docker ec2-user
  - "yum -y groupinstall \"Development Tools\""
  - pip3 install pgcli psycopg2-binary keyrings.alt boto3 'awscli>=1.15'
  
  # Pull the registration API
  - git clone https://github.com/ChicagoWorldcon/registration-api /opt/registration/registration-api
  - chown -R ec2-user /opt/registration/registration-api
  
  # Bring up docker last
  - systemctl enable docker
  - systemctl start docker
  
  # ensure we have certificates
  - systemctl start letsencrypt
  
  # bring up the reg API
  - systemctl enable registration
  - systemctl start registration


write_files:
  - encoding: b64
    content: "${letsencrypt_service}"
    path: /etc/systemd/system/letsencrypt.service
    permissions: '0644'

  - encoding: b64
    content: "${letsencrypt_timer}"
    path: /etc/systemd/system/letsencrypt.timer
    permissions: '0644'

  - encoding: b64
    content: "${registration_service}"
    path: /etc/systemd/system/registration.service
    permissions: '0644'

  - encoding: b64
    content: "${docker_daemon_json}"
    path: /etc/docker/daemon.json
    permissions: 0644

  - encoding: b64
    content: "${service_env_vars}"
    path: /etc/chicago/service-env.sh
    permissions: '0644'

  - encoding: b64
    content: "${service_env_file}"
    path: /etc/chicago/service-env-file
    permissions: '0644'

  - encoding: b64
    content: "${db_env_vars}"
    path: /etc/chicago/db-env.sh
    permissions: '0644'

  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/${db_username}/${stage} | jq -r .SecretString)
        exec pgcli -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/db
    permissions: '0755'

  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${project}/db/${db_name}/${db_username}/${stage} | jq -r .SecretString)
        exec psql -h ${db_hostname} -U ${db_username} ${db_name} "$@"
    path: /usr/local/bin/psql.reg
    permissions: '0755'

  - content: |
        #!/bin/bash
        . /etc/chicago/db-env.sh
        exec psql -h ${db_hostname} -U ${db_admin_username} ${db_name} "$@"
    path: /usr/local/bin/psql.admin
    permissions: '0755'

  - content: |
        set-option -g prefix C-o
        bind-key C-o send-key C-o
    path: /etc/tmux.conf
    permissions: '0644'

  - content: |
        export AWS_DEFAULT_REGION=${aws_region}
    path: /etc/profile.d/set-aws-region.sh
    permissions: '0644'

output : { all : '| tee -a /var/log/cloud-init-output.log' }
