#cloud-config
package_update: true
package_upgrade: true

packages:
  - awscli
  - build-essential
  - docker-compose
  - docker.io
  - libpq-dev
  - jq
  - postgresql-client-12
  - python-is-python3
  - python3
  - python3-dev
  - python3-pip
  - ruby
  - tmux
  - wget

write_files:
  - encoding: b64
    content: "${instance_launch_script}"
    path: /var/lib/cloud/scripts/per-instance/00-bootstrap.sh
    permissions: '0755'

  - encoding: b64
    content: "${install_codedeploy_script}"
    path: /var/lib/cloud/scripts/per-instance/01-install-codedeploy.sh
    permissions: '0755'

  - encoding: b64
    content: "${caddyfile}"
    path: /opt/chicago/etc/Caddyfile
    permissions: '0644'

  - encoding: b64
    content: "${registration_service}"
    path: /etc/systemd/system/registration.service
    permissions: '0644'

  - encoding: b64
    content: "${docker_daemon_json}"
    path: /etc/docker/daemon.json
    permissions: 0644

  - encoding: b64
    content: "${rotate_creds}"
    path: /opt/chicago/bin/rotate-creds.sh
    permissions: '0755'

  - encoding: b64
    content: "${docker_compose}"
    path: /opt/chicago/app/docker-compose.yml
    permissions: '0644'

  - encoding: b64
    content: "${service_env_file}"
    path: /opt/chicago/etc/service.env
    permissions: '0644'

  - encoding: b64
    content: "${www_env_file}"
    path: /opt/chicago/etc/www.env
    permissions: '0644'

  - encoding: b64
    content: "${sidekiq_env_file}"
    path: /opt/chicago/etc/sidekiq.env
    permissions: '0644'

  - content: |
      # Times when the Hugo Nominations and Voting pages will become active for members
      HUGO_NOMINATIONS_OPEN_AT=2021-12-31T23:59:00-08:00
      HUGO_VOTING_OPEN_AT=2022-03-13T11:59:00-08:00
      HUGO_CLOSED_AT=2022-08-02T12:00:00+13:00

      # Instalment amounts for users to choose from
      # If not specified, defaults to $75 and $50
      INSTALMENT_MIN_PAYMENT_CENTS=7500
      INSTALMENT_PAYMENT_STEP_CENTS=5000

      # add post-install env vars here needed to launch. Above here are bugs, but we need them at the moment
  
    path: /opt/chicago/etc/overrides.env
    permissions: '0644'

  - encoding: b64
    content: "${db_env_vars}"
    path: /opt/chicago/etc/db-env.sh
    permissions: '0644'

  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${db_superuser_secret} | jq -r .SecretString)
        exec pgcli -h ${db_hostname} -U ${db_superuser_username} "$@"
    path: /usr/local/bin/db.admin
    permissions: '0755'

  - content: |
        #!/bin/bash
        export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${db_superuser_secret} | jq -r .SecretString)
        exec psql -h ${db_hostname} -U ${db_superuser_username} "$@"
    path: /usr/local/bin/psql.admin
    permissions: '0755'

  - content: |
        #!/bin/bash
        . /opt/chicago/etc/db-env.sh
        exec pgcli -h ${db_hostname} -U ${db_site_username} ${db_name} "$@"
    path: /usr/local/bin/db
    permissions: '0755'

  - content: |
        #!/bin/bash
        . /opt/chicago/etc/db-env.sh
        exec psql -h ${db_hostname} -U ${db_site_username} ${db_name} "$@"
    path: /usr/local/bin/psql.site
    permissions: '0755'

  - content: |
      #!/bin/bash
      docker run --rm -it \
          --env-file=/opt/chicago/etc/creds.env \
          --env-file=/opt/chicago/etc/www.env \
          --env-file=/opt/chicago/etc/service.env \
          --env-file=/opt/chicago/etc/overrides.env \
          registry.gitlab.com/worldcon/2020-wellington:latest /bin/sh
    path: /opt/chicago/bin/rails.admin
    permissions: '0755'

  - content: |
        set-option -g prefix C-o
        bind-key C-o send-key C-o
    path: /etc/tmux.conf
    permissions: '0644'

  - content: |
        export AWS_DEFAULT_REGION=${aws_region}
    path: /etc/profile.d/set-aws-region.sh
    permissions: '0644'

  - encoding: b64
    content: "${prompt_file}"
    path: /etc/profile.d/set-instance-prompt.sh
    permissions: '0644'

  - content: |
        export PATH=/opt/chicago/bin:/usr/pgsql-9.6/bin:$PATH
    path: /etc/profile.d/chicago-paths.sh
    permissions: '0644'
